#!/bin/sh

infile="$1"
outfile="$2"

if [ -z "$infile" ]; then
    echo "Usage: midi2mp3 INFILE [OUTFILE]"
    exit
fi

if [ -z "$outfile" ]; then
    outfile="$(echo "$infile" | sed -e 's/\.[^.]*$//').mp3"
    echo "No outfile provided. Will default to: $outfile"
fi

timidity "$infile" -Ow -o - | ffmpeg -i - -acodec libmp3lame -ab 256k "$outfile"
