#!/bin/sh

vidfile="$1"
start_ts="$2"
outfile="$(echo "$vidfile" | sed -e 's/\.[^.]*$//')_thumb.png"

if [ -z "$vidfile" ]; then
    echo "Usage: vidthumb VIDEO_FILE [OUTPUT_IMAGE_FILE] [START_TIMESTAMP]"
    exit
fi

if [ -z "$start_ts" ]; then
    start_ts="0"
fi

ffmpeg -i "$vidfile" -vframes 1 -f image2 -ss "$start_ts" "$outfile"

if [ $? -eq 0 ]; then
    echo "Thumbnail saved to: "$outfile""
fi
